name: Check Release PR source branch
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited
jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        run: |
          if [ ${{ github.base_ref }} == "prod" ] && [ ${{ github.head_ref }} != "main" ]; then
            echo "Merge requests to prod branch are only allowed from main branch."
            exit 1
          fi